# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yu-Jie, Zheng
title: CS Student, Full Stack Engineer
email: jackleagends@gmail.com
# email_title: Email (Email title override)
phone: +886 978735622
# phone_title: Phone (Phone title override)
website: yjack0000.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: ./
github_username:  YJack0000
#stackoverflow_username: "yjack0000"
#dribbble_username: yjack0000
facebook_username: YJack0000
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: é„­å®‡å‚‘ (YJack) 
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am Yu-Jie you can call me YJ. I am Bachelor of National Cheng-Chi University, Taiwan. I have exposed to a wide range of developer skilled such as C++, Machine learning, Full Stack Development, Javascript and its frameworks. 
  
  ðŸ”­ What do I do and What have I done?
  * Iâ€™m currently working on combining opencv and arduino to make an game-assistant in [Lary Technology](https://github.com/Lary-Tech). 
  * Iâ€™m currently working on [CeranaPOS](https://github.com/CeranaPOS) which is a simple, convenient and fast online POS service. And all backend are  using Firebase services such as Hosting, Cloud Function, Firestore, Firebase Authentication. 
  * Iâ€™m currently trying to do fencing-action-recognition by using [mediapipe](https://github.com/google/mediapipe) and [yolo](https://github.com/ultralytics/yolov5). And you can find my research proposal [here](https://github.com/YJack0000/fencing_pose_detection/blob/main/Research%20Proposal.md).

  ðŸ“« I'm mainly use [Vue](https://github.com/vuejs/vue) + [Vite](https://github.com/vitejs/vite) + [Pinia](https://github.com/vuejs/pinia) + [Element-plus](https://github.com/element-plus/element-plus) to craete backstage management system. 

  ðŸ’¬ One line that describes me best?
  * I would describe myself as innovative, adaptable to change, a fast learner, and someone who is prepared to go above and beyond what is required to ensure my skills always stays one step ahead of my peers.ðŸ˜‰ðŸ˜‰
  
content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Hardware-based game assistant
        link: https://shopee.tw/mooonphase?categoryId=100634&entryPoint=ShopByPDP&itemId=17420247260&upstream=search
        link_text: market on shopee
        additional_links:
          - title:  Cerana
            icon: fas fa-home
            url: https://lineagew-cv.web.app/sign-in
        quote: >
          To help loyal players easily spawn monsters and install software scripts that do not violate official regulations, this hardware-oriented game assistant is designed. There are currently more than 100 users.
        description: | # this will include new lines to allow paragraphs
          Co-designed and sold products with the seniors of the school team. 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: CeranaPOS
        link: https://ceranapos.web.app/
        link_text: webpage under development
        additional_links:
          - title:  Cerana
            icon: fab fa-github
            url: https://github.com/CeranaPOS
        quote: >
          The continuation of the DBMS course project will be launched at the Christmas market.
          CeranaPOS is a simple, convenient and fast online POS service. Do you set up a stall in a small market or do some short-term transactions, but find that the invoicing system on the market is expensive and unnecessary? Purchase, sales, profit management, employee management, all you need is a laptop or tablet to easily meet your needs!
        description: | # this will include new lines to allow paragraphs
          Trying to introduce full Firebase for backend and Github action for CI in this project. 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Fencing scoring machine
        link: https://docs.google.com/presentation/d/1Hf-E8gC1xCY9yOvOedSuTTo_0vpAPJ7h4CE3p-vytfw/edit?usp=sharing
        link_text: slide
        quote: >
          It is not necessary to get an expensive electronic scoring device from the school club every time I practice.
        description: | # this will include new lines to allow paragraphs
          Together with my GDSC friend, use Arduino and 3D printing to design a very low-cost electronic review device. 
  - title: Experience
    layout: list
    content:
      - layout: right
        title: è³´ç‘žç§‘æŠ€
        sub_title: Project Development Manager
        caption: Dec 2021 - Present
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          The hardware game assistant develops and determines the technology used by the team.     
          **Skills: C++ Â· Arduino Â· Cloud Functions Â· Vue.js Â· CI/CD Â· ld3322**
      - layout: right
        title: æ±æ³°
        sub_title: Project Intern
        caption: Sep 2021 - Aug 2022 
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Making web application for companies to manage IOT sensors and gateways. 
      - layout: right
        title: OHGA SMARTTHINGS CO., LTD
        sub_title: Intern
        caption: Jul 2021 - Sep 2021
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Make website using Vue.js and Express.js for IOT monitoring. 
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: National Chengchi University
        sub_title: BA Computer Science
        caption: 2018-2022
        #quote: >
        #  Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
        #  Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      * I'm currently a active fencer who will participate most of the National Ranking Tournament.
      * I have the same painting as my avatar on my fencing mask. <img src="images/Mask.png" height="70" />
      * My favorite keyboard brand is Leopold and I'm currently using FC660M as my main production tools. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
